### ISSUE TITLE
System.InvalidOperationException: 'Could not find color or style '0'.

### ISSUE THREAD

**Issue by Bia10** [spectresystems/spectre.console#312]
![image](https://user-images.githubusercontent.com/2548763/112107538-5c5bf480-8baf-11eb-8d2c-5eddc5bac912.png)

Caused by this

```c#
 AnsiConsoleExtensions.Log($"Data[0]: {_data[0]}", "info");
```

basically

```c#
AnsiConsole.MarkupLine($"[white]{timeStampFull}-{severity.ToUpper()}:[/] {message} [white]...[/]");
```
doesn't like the extra braces but why should that matter?

the number of opening markup tokens should matchup the number of closing tokens, if there are more then these are likely part of the message even more so if they contain no valid markup tag

**Comment by patriksvensson** [comment]
It doesn't consider "0" to be a valid style. You will need to escape the brackets for the markup expression to be valid: `[[Foo]]`

**Comment by Bia10** [comment]
Well basically my program generates json arrays so how do I conveniently display them in markup?

**Comment by patriksvensson** [comment]
You'll have to escape it: ` `mystring.EscapeMarkup()` or `Markup.Escape(myString)`.

See the section "Escaping format characters" at https://spectresystems.github.io/spectre.console/markup for more information.

**Comment by Bia10** [comment]
Thx.

**Comment by gitfool** [comment]
I'm also seeing this exception:
```
user@3c4278e7f17c:~/gemini$ ./gemini config alpha
System.InvalidOperationException: Could not find color or style '0'.
  at Spectre.Console.StyleParser.Parse(String text)
  at Spectre.Console.MarkupParser.Parse(String text, Style style)
  at Spectre.Console.Markup..ctor(String text, Style style)
  at Spectre.Console.TableExtensions.<>c.<AddRow>b__5_0(String column)
  at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
  at System.Linq.Enumerable.ToArray[[TSource]](IEnumerable`1 source)
  at Spectre.Console.TableExtensions.AddRow(Table table, String[] columns)
  at Pharos.Gemini.ConfigCommand.OnExecute(CommandContext context, Settings settings)
  at Pharos.Gemini.CommandBase`1.Execute(CommandContext context, TSettings settings)
```
... for code that used to work:
```c#
public sealed partial class ConfigCommand : CommandBase<ConfigCommand.Settings>
{
    public ConfigCommand(IOptions<Config> options, ILogger<ConfigCommand> logger) : base(options, logger) { }

    protected override int OnExecute(CommandContext context, Settings settings)
    {
        var table = new Table().AddColumn("Key").AddColumn("Value");
        foreach (var (key, value) in Config.ToTokens())
        {
            table.AddRow(key, value.ToValueString());
        }
        AnsiConsole.Render(table);
        return 0;
    }
}
```
But fails with latest alpha of [Spectre.Console](https://www.nuget.org/packages/Spectre.Console).

@patriksvensson did something change that broke this or am I missing something?

**Comment by gitfool** [comment]
It just occurred to me that it's probably related to the dictionary keys and values I'm using:
```c#
Config.ToTokens().ToDictionary(entry => entry.Key, entry => entry.Value.ToValueString()).ToJson();
```
yields:
```json
{
  "Commands.Deploy.Repair[0]": "code.cmd",
  "Commands.Deploy.Repair[1]": "--new-window",
  "Commands.Deploy.Repair[2]": "--wait",
  "Environment.Name": "alpha",
  "Environment.DisplayName": "Alpha",
  "Environment.Type": "Development",
  "Environment.CostCenter": "Beacon",
  "Environment.Aws.AssumeRoleArn": "arn:aws:iam::REDACTED:role/deployer",
  "Environment.Aws.AccountId": "REDACTED",
  "Environment.Aws.Region": "us-west-2",
  "Environment.Aws.Ec2.InstanceType": "t3.medium",
  "Environment.Aws.Ec2.KeyName": "beacon-oregon",
  "Environment.Aws.Eks.AutoScaling.DesiredCapacity": "1",
  "Environment.Aws.Eks.AutoScaling.MinSize": "1",
  "Environment.Aws.Eks.AutoScaling.MaxSize": "1",
  "Environment.K8s.Version": "1.20",
  "Pulumi.Organization.Name": "pharos",
  "Pulumi.Organization.DisplayName": "Pharos"
}
```
