### ISSUE TITLE
Links with a link as the text fails

### ISSUE THREAD

**Issue by phil-scott-78** [spectresystems/spectre.console#82]
Trying to do this markup fails because it thinks it might be an emoji - `Hello [link=http://example.com]http://example.com[/]`

Failing test - https://github.com/phil-scott-78/spectre.console/commit/1f5e00e6f0c6912a43f65f7c833f690d2bab99db

Exception
```
System.Collections.Generic.KeyNotFoundException
The given key '//example.com]http' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Spectre.Console.Emoji.<Replace>g__ReplaceEmoji|1_0(Match match) in R:\Projects\spectre.console\src\Spectre.Console\Emoji.cs:line 19
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Spectre.Console.Emoji.Replace(String value) in R:\Projects\spectre.console\src\Spectre.Console\Emoji.cs:line 20
   at Spectre.Console.Internal.MarkupParser.Parse(String text, Style style) in R:\Projects\spectre.console\src\Spectre.Console\Internal\Text\Markup\MarkupParser.cs:line 16
   at Spectre.Console.Markup..ctor(String text, Style style) in R:\Projects\spectre.console\src\Spectre.Console\Widgets\Markup.cs:line 35
   at Spectre.Console.Tests.Unit.MarkupTests.Should_render_links_as_expected(String input, String output) in R:\Projects\spectre.console\src\Spectre.Console.Tests\Unit\MarkupTests.cs:line 33
```

**Comment by patriksvensson** [comment]
@phil-scott-78 Thanks for reporting this. I have fixed the bug and the patched code should be available in 0.21.1 👍
