### ISSUE TITLE
Grids/Table: Exception gets thrown when console width is very small

### ISSUE THREAD

**Issue by toburger** [spectresystems/spectre.console#93]
An Exception gets thrown when running the Grids or Table example on a very small console window:

Grid:
> System.InvalidOperationException: Text folding failed since 'take' was zero.

Table:
> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')

![image](https://user-images.githubusercontent.com/728782/95180118-d515f280-07c1-11eb-91e4-b2d57e1b5f75.png)

I don't expect pretty output but at least the program shouldn't crash.

**Comment by patriksvensson** [comment]
@toburger Yup, it shouldn't crash. Will take a look at it when I have some free time.

**Comment by patriksvensson** [comment]
@toburger @khalidabuhakmeh This should be fixed with #99.
I've just pushed a new release, so it will be available on NuGet in about 15 minutes.

**Comment by toburger** [comment]
Thx! Panel is now working, but Tables throws still an exception:

```
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Spectre.Console.Rendering.Segment.SplitOverflow(Segment segment, Nullable`1 overflow, RenderContext context, Int32 width) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Segment.cs:line 312
   at Spectre.Console.Paragraph.SplitLines(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Paragraph.cs:line 245
   at Spectre.Console.Paragraph.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Paragraph.cs:line 141
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Renderable.cs:line 19
   at Spectre.Console.Markup.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Markup.cs:line 47
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Renderable.cs:line 19
   at Spectre.Console.Table.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Table.cs:line 197
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Renderable.cs:line 19
   at Spectre.Console.Table.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Table.cs:line 197
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Renderable.cs:line 19
   at Spectre.Console.Table.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Widgets\Table.cs:line 197
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Rendering\Renderable.cs:line 19
   at Spectre.Console.AnsiConsoleExtensions.Render(IAnsiConsole console, IRenderable renderable) in C:\Workspace\oss\spectre.console\src\Spectre.Console\Extensions\AnsiConsoleExtensions.Rendering.cs:line 30
   at Spectre.Console.AnsiConsole.Render(IRenderable renderable) in C:\Workspace\oss\spectre.console\src\Spectre.Console\AnsiConsole.Rendering.cs:line 16
   at TableExample.Program.RenderNestedTable() in C:\Workspace\oss\spectre.console\examples\Tables\Program.cs:line 87
   at TableExample.Program.Main() in C:\Workspace\oss\spectre.console\examples\Tables\Program.cs:line 16
```

![image](https://user-images.githubusercontent.com/728782/95720995-43e7c580-0c72-11eb-8cc3-cd78d1c274b1.png)

**Comment by patriksvensson** [comment]
@toburger This should be fixed now. Would you mind taking it for a spin to verify?

**Comment by toburger** [comment]
I can confirm that the bug is fixed! 👍
